### ISSUE TITLE
GAP-NDP: About epsilon setting.

### ISSUE THREAD

**Issue by W11Dr** [sisaman/GAP#3]
Hi, I'm wondering why I set epsilon from [2,4,8] but getting the same model accuracy.
I just try this:
    python train.py gap-ndp --dataset facebook --epsilon 8 --encoder_epochs 10 --epochs 10
Meanwhile, I find that noise_sacle is always 0.000. 
ps: waht is 'set_all_representation' in the code?

**Comment by sisaman** [comment]
It's weird, as you should get different, non-zero noise scales for different epsilon values.
Could you uninstall `autodp` and install it again with `pip install git+https://github.com/yuxiangw/autodp`?

`self.set_all_representation(mech)` sets the function representation of the self mechanism to be the same as that of `mech`. It simply does the following:
```
self.approxDP = mech.approxDP
self.RenyiDP = mech.RenyiDP
self.fDP = mech.fDP
self.eps_pureDP = mech.eps_pureDP
self.delta0 = mech.delta0
```

**Comment by W11Dr** [comment]
Thank you for your instruction! 
I've manually updated `autodp` and solve the problem.
***
To be specific, the function `set_all_representation` is not well defined in the previous version of `autodp`, so the DP noise is not set correctly.
