### ISSUE TITLE
Cannot import 'to_csc' from 'torch_geometric.loader.utils'

### ISSUE THREAD

**Issue by jianxinwei** [sisaman/GAP#6]
Hi, when running the 'train.py', it says 'ImportError: cannot import name 'to_csc' from 'torch_geometric.loader.utils'. The torch_geometric.loader does not contain utils and to_csc.
Thanks.

**Comment by sisaman** [comment]
What version of PyTorch Geometric are you using?
You should not have this issue if using torch_geometric 2.1.0.
However, in torch_geometric 2.2.0, `to_csc` has been moved to `torch_geometric.sampler.utils`.

**Comment by jianxinwei** [comment]
I used torch_geometric 2.2.0. The issue is resolved when I reinstalled 2.1.0. Thanks for your quick reply!
