### ISSUE TITLE
Exact hyperparameters for Table 2?

### ISSUE THREAD

**Issue by elichienxD** [sisaman/GAP#7]
Hi @sisaman ,

I wonder if you can provide the hyperparameters for reproducing the results of Table 2 in your paper. I notice that you have already provided the hyperparameters in ``./GAP/test/train/gap-*.sh`` for the facebook dataset. Is it possible to also provide those for reddit and amazon datasets? It would be a great help for us to reproduce your results in Table 2.

Best,
Eli

**Comment by sisaman** [comment]
I added a script containing the run commands to reproduce the results in Table 2.
You can find it at [test/train/table2.sh](https://github.com/sisaman/GAP/blob/master/test/train/table2.sh).

**Comment by elichienxD** [comment]
Hi @sisaman ,

Thank you so much for your timely response and help! Wish you have a great day :)

Best,
Eli
