### ISSUE TITLE
Can not install autodp with version >= 2.1.0

### ISSUE THREAD

**Issue by khangtran2020** [sisaman/GAP#8]
I tried to install the `requirement.txt`, but it couldn't install `autodp` with version `2.1.0b0`. Basically, it's a problem of autodp. When I tried to run with `autodp` version `2.0`, the scipy optimizer can not `minimizer_scaler` with method `Brent` or `Bounded`. Is there any option that I can sneak through the use of autodp?

**Comment by sisaman** [comment]
Please install the latest version of AutoDP directly from GitHub:
`pip install git+https://github.com/yuxiangw/autodp`

Also, please install scipy=1.9.1 as AutoDP is not compatible with the newer versions of scipy.

**Comment by khangtran2020** [comment]
Thank you, I could run it now, just need to downgrade scipy to 1.9.1
